name: Convert Jupyter README

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies & Convert README.ipynb
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          jupyter nbconvert --template="pythoncodeblock.tpl" --ClearMetadataPreprocessor.enabled=True --ClearOutput.enabled=True  --to markdown MNIST_Classify_AutoEncoder.ipynb --output="README.md"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md README_files
          git commit -m "Convert MNIST_Classify_AutoEncoder.ipynb to README.md" -a
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.ACCESS_TOKEN }}
